const FilteringHotelDocs = [
    {
        id: 1,
        title: 'Coxs bazzer hotel',
        location: 'eita holo location',
        sublocation: 'it is sub location coxbazzer ',
        discountPrice: '150',
        Price: '7000',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/alexandra-gorn-JIUjvqe2ZHg-unsplash.jpg'),
        starCategory: 'one-star'
    },
    {
        id: 2,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'eita holo price tillte',
        percentage: '15% up 17%',
        Image: require('../../Images/r-umut-tuluoglu-ND5hWrvknqM-unsplash.jpg'),
        starCategory: 'two-star'
    },
    {
        id: 3,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/mehrab-sium-v9h8R5xpvVI-unsplash (1).jpg'),
        starCategory: 'three-star'
    },
    {
        id: 4,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/nuddle-GcSQT8UFP7s-unsplash.jpg'),
        starCategory: 'four-star'
    },
    {
        id: 5,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/sidekix-media-szG9kzMLcPE-unsplash.jpg'),
        starCategory: 'five-star'
    },
    {
        id: 6,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/anshita-nair-Jo_GA0TDTgM-unsplash.jpg'),
        starCategory: 'five-star'
    },
    {
        id: 7,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/alexandra-gorn-JIUjvqe2ZHg-unsplash.jpg'),
        starCategory: 'five-star'
    },
    {
        id: 8,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/bench-accounting-nvzvOPQW0gc-unsplash.jpg'),
        starCategory: 'five-star'
    },
    {
        id: 9,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/alexandra-gorn-JIUjvqe2ZHg-unsplash.jpg'),
        starCategory: 'two-star'
    },
    {
        id: 10,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/mehrab-sium-v9h8R5xpvVI-unsplash (1).jpg'),
        starCategory: 'three-star'
    },
    {
        id: 11,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/mehrab-sium-v9h8R5xpvVI-unsplash.jpg'),
        starCategory: 'three-star'
    },
    {
        id: 12,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/pavel-neznanov-OK9l62v5fLU-unsplash.jpg'),
        starCategory: 'four-star'
    },
    {
        id: 13,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/r-umut-tuluoglu-ND5hWrvknqM-unsplash.jpg'),
        starCategory: 'four-star'
    },
    {
        id: 14,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/sidekix-media-szG9kzMLcPE-unsplash.jpg'),
        starCategory: 'four-star'
    },
    {
        id: 15,
        title: 'this is hotel tittle one',
        location: 'this is location',
        sublocation: 'it is sub location ',
        discountPrice: 'BDT-150',
        Price: 'BDT-1500',
        priceTitle: 'this is sub tittle',
        percentage: '15% up 17%',
        Image: require('../../Images/anshita-nair-Jo_GA0TDTgM-unsplash.jpg'),
        starCategory: 'five-star'
    },
]
export default FilteringHotelDocs;